version: '3.3'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ski/.env

  web:
    build: .
    restart: always
    command: sh -c "python manage.py migrate && gunicorn ski.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/static/
      - static_volume:/app/media/
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ski/.env

  nginx:
    build: nginx
    volumes:
      - static_volume:/app/static
      - static_volume:/app/media/
    ports:
      - "80:80"
    depends_on:
      - web